#include <vcl.h>
#include <tchar.h>
#include <htmlhelp.h>
#include <math.h>
#include <utilcls.h>
#include <algorithm>
#include <memory>
#include <RegularExpressions.hpp>
#include <System.IOUtils.hpp>
#include <System.StrUtils.hpp>
#include <System.Win.Registry.hpp>
#include <Vcl.Clipbrd.hpp>
#include <Vcl.FileCtrl.hpp>
#include <Vcl.Printers.hpp>
